#!/usr/bin/env bash
#The 4 parameter required
#     1. The path to the file to be transferred
#     2. The IP of the server we want to transfer the file to
#     3. The username scp connects with
#     4. The path to the SSH private ket that scp uses

path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
file="$1"
ip="$2"
user="$3"
key="$4"
brown='\e[0;33m'
reset='\033[0m'

if [ $# -lt 4 ]
then
	echo -e "Usage:${brown}0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
else
	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
fi
