#!/usr/bin/env bash
# Bash script that install and configure HAproxy

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6

sudo apt-get -y install haproxy=2.6.\*

str_haproxy="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 47185-web-01 3.235.64.111:80 check\n\tserver 47185-web-02 52.90.23.35:80 check"
echo -e "$str_haproxy" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart

