#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process using the kill command

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
    kill "$pid"
    echo "Terminated."
else
    echo "No $pid process found."
fi
