#!/usr/bin/env bash
# Find the PID of the running 4-to_infinity_and_beyond process

PID=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$PID" ]; then
    echo "0" > /proc/"$PID"/oom_score_adj 2>/dev/null && echo "Terminated."
else
    echo "No running process:4-to_infinity_and_beyond."
fi

