#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

HOUR=0
while [ $HOUR -le 12 ]
do
    echo "Hour: $HOUR"
    MINUTES=1
	while [ $MINUTES -le 59 ]
	do
		echo "$MINUTES"
		MINUTES=$((MINUTES + 1))
	done
	HOUR=$((HOUR + 1))
done
